server.port=8083

# H2 Database configuration for parking-service
spring.datasource.url=jdbc:h2:mem:parkingdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Register with Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
